ignored = ["github.com/xgfone/websocket"]

[[constraint]]
    name = "github.com/xgfone/logger"
    version = "v2.2.0"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "v6.6.0"

[[constraint]]
    name = "github.com/xgfone/ship"
    version = "v1.0.0"

[[constraint]]
    name = "github.com/xgfone/go-config"
    version = "v9.3.1"
