[[constraint]]
    name = "github.com/xgfone/logger"
    branch = "v1.0.0"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "v6.6.0"

[[constraint]]
    name = "github.com/xgfone/websocket"
    branch = "master"
